# Generated by Django 3.2.5 on 2021-07-12 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
